header = ['','', '', 'status', 'publication-date', 'exclusion', '', 'provider-definition', 'notes']
header = header[1:]
organisation_rows = ['','','','','','','', 'total-budget', 'recipient-org-budget', 'recipient-country-budget', 'documents'] 
activity_rows = [
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'Identification',
    'Reporting Organisation',
    'IATI activity identifier',
    'Other activity identifiers',
    'Basic Activity Information',
    'Activity Title (Agency language)',
    'Activity Title (Recipient language)',
    'Activity Description (Agency language)',
    'Activity Description (Recipient language)',
    'Activity Status',
    'Activity Dates (Start Date)',
    'Activity Dates (End Date)',
    'Activity Contacts',
    'Participating Organisation (Funding)',
    'Participating Organisation (Extending)',
    'Participating Organisation (Implementing)',
    'Participating Organisation (Accountable)',
    'Geopolitical Information',
    'Recipient Country',
    'Recipient Region',
    'Sub-national Geographic Location',
    'Classifications',
    'Sector (CRS)',
    'Sector (Agency specific)',
    'Policy / Thematic Markers',
    'Collaboration Type',
    'Default Flow Type',
    'Default Finance Type',
    'Default Aid Type',
    'Default Tied Aid Status',
    'Financial',
    'Activity Budget',
    'Planned Disbursements',
    '(UNDER DEVELOPMENT) Recipient Country Budget Identifier',
    'Financial Transaction',
    'Financial transaction (Commitment)',
    'Financial transaction (Disbursement & Expenditure)',
    'Financial transaction (Reimbursement)',
    'Financial transaction (Incoming Funds)',
    'Financial transaction (Loan repayment / interest repayment)',
    'Related Documents',
    'Activity Documents',
    'Activity Website',
    'Related Activity',
    'Performance',
    'Conditions attached Y/N',
    'Text of Conditions',
]

date_tags = [ 'publication-date' ]
codes = {
        'status': { 'NO':'N', 'PARTIAL':'P', 'YES':'Y' }
    }
